// Code generated by mockery v2.9.4. DO NOT EDIT.

package server

import mock "github.com/stretchr/testify/mock"

// MockStorageAdapter is an autogenerated mock type for the StorageAdapter type
type MockStorageAdapter struct {
	mock.Mock
}

// StoreHostTelemetry provides a mock function with given fields: _a0
func (_m *MockStorageAdapter) StoreHostTelemetry(_a0 *HostTelemetry) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*HostTelemetry) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
