{
 "title": "Trento telemetry (PostgresQL data)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "flavor", "label": "Flavor", "query": "Community,Premium" }
  ]
 },
 "panels": [
  {
   "title": "Installations number by day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('day', time) as time, count(distinct(payload->'installation_id'))\nFROM telemetry\nWHERE\n  $__timeFilter(time) and payload->>'installation_flavor' ~* '${flavor:raw}'\nGROUP BY DATE_TRUNC ('day', time)\n"
    }
   ]
  },
  {
   "title": "Agents number by day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('day', time) as time, count(distinct(payload->'agent_id'))\nFROM telemetry\nWHERE\n  $__timeFilter(time) and payload->>'installation_flavor'  ~* '${flavor:raw}'\nGROUP BY DATE_TRUNC ('day', time)\n\n"
    }
   ]
  },
  {
   "title": "Cloud providers",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  payload->'cloud_provider' AS metric,\n  COUNT(DISTINCT(payload->'agent_id')) AS value\nFROM telemetry\nWHERE\n  $__timeFilter(time) and payload->>'installation_flavor'  ~* '${flavor:raw}'\nGROUP BY payload->'cloud_provider'"
    }
   ]
  },
  {
   "title": "SLES versions",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  payload->'sles_version' AS metric,\n  COUNT(DISTINCT(payload->'agent_id')) AS value\nFROM telemetry\nWHERE\n  $__timeFilter(time) and payload->>'installation_flavor' ~* '${flavor:raw}'\nGROUP BY payload->'sles_version'"
    }
   ]
  },
  {
   "title": "Total memory MB",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  payload->'total_memory_mb' AS metric,\n  COUNT(DISTINCT(payload->'agent_id')) AS value\nFROM telemetry\nWHERE\n  $__timeFilter(time) and payload->>'installation_flavor' ~* '${flavor:raw}'\nGROUP BY payload->'total_memory_mb'\n"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  payload->'cpu_count' AS metric,\n  COUNT(DISTINCT(payload->'agent_id')) AS value\nFROM telemetry\nWHERE\n  $__timeFilter(time) and payload->>'installation_flavor' ~* '${flavor:raw}'\nGROUP BY payload->'cpu_count'\n"
    }
   ]
  },
  {
   "title": "Agent installation source",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(payload->'agent_installation_source', '\"Unknown\"') AS metric,\n  COUNT(DISTINCT(payload->'agent_id')) AS value\nFROM telemetry\nWHERE\n  $__timeFilter(time) and payload->>'installation_flavor' ~* '${flavor:raw}'\nGROUP BY payload->'agent_installation_source'\n"
    }
   ]
  }
 ]
}