{
 "title": "Trento telemetry",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "flavor", "label": "Flavor", "query": "Community,Premium" }
  ]
 },
 "panels": [
  {
   "title": "Installations number",
   "type": "timeseries",
   "description": "The number of different Trento installations",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"host_telemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"installation_flavor\" or r[\"_field\"] == \"cloud_provider\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.installation_flavor =~ /${flavor:raw}/)\n  |> duplicate(column: \"cloud_provider\", as: \"_value\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: unique, column: \"installation_id\")\n  |> aggregateWindow(every: 1d, fn: count)\n  |> rename(columns: {_time: \"time\"})"
    }
   ]
  },
  {
   "title": "Agents number",
   "type": "timeseries",
   "description": "Number of registered agents",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"host_telemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"installation_flavor\" or r[\"_field\"] == \"cloud_provider\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.installation_flavor =~ /${flavor:raw}/)\n  |> duplicate(column: \"cloud_provider\", as: \"_value\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: unique, column: \"agent_id\")\n  |> aggregateWindow(every: 1d, fn: count)\n  |> rename(columns: {_time: \"time\"})"
    }
   ]
  },
  {
   "title": "Agents number by provider (last values)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "g_field = \"cloud_provider\"\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"host_telemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"installation_flavor\" or r[\"_field\"] == g_field)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.installation_flavor =~ /${flavor:raw}/)\n  |> duplicate(column: g_field, as: \"_value\")\n  |> last()\n  |> duplicate(column: \"_value\", as: g_field)\n  |> group(columns: [g_field])\n  |> count()\n  |> rename(columns: {_value: \"\"})\n"
    }
   ]
  },
  {
   "title": "Agents by SLES version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "g_field = \"sles_version\"\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"host_telemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"installation_flavor\" or r[\"_field\"] == g_field)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.installation_flavor =~ /${flavor:raw}/)\n  |> duplicate(column: g_field, as: \"_value\")\n  |> last()\n  |> duplicate(column: \"_value\", as: g_field)\n  |> group(columns: [g_field])\n  |> count()\n  |> rename(columns: {_value: \"\"})\n"
    }
   ]
  },
  {
   "title": "Agents by Total Memory on MB",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "g_field = \"total_memory_mb\"\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"host_telemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"installation_flavor\" or r[\"_field\"] == g_field)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.installation_flavor =~ /${flavor:raw}/)\n  |> duplicate(column: g_field, as: \"_value\")\n  |> last()\n  |> duplicate(column: \"_value\", as: g_field)\n  |> group(columns: [g_field])\n  |> count()\n  |> rename(columns: {_value: \"Total memory MB\"})"
    }
   ]
  },
  {
   "title": "Agents by CPU count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "g_field = \"cpu_count\"\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"host_telemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"installation_flavor\" or r[\"_field\"] == g_field)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.installation_flavor =~ /${flavor:raw}/)\n  |> duplicate(column: g_field, as: \"_value\")\n  |> last()\n  |> duplicate(column: \"_value\", as: g_field)\n  |> group(columns: [g_field])\n  |> count()\n  |> rename(columns: {_value: \"CPU count\"})"
    }
   ]
  }
 ]
}